include: package:flutter_lints/flutter.yaml

analyzer:
  exclude:
    - build/**
  errors:
    invalid_annotation_target: ignore

linter:
  rules:
    prefer_final_locals: true
    prefer_final_in_for_each: true
    require_trailing_commas: true
    avoid_print: true
