name: nms
description: Shared half-hour prayer calendar with Firebase backend.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=3.3.0 <4.0.0"
  flutter: ">=3.19.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  firebase_core: ^4.1.1
  firebase_auth: ^6.1.0
  cloud_firestore: ^6.0.2
  firebase_messaging: ^16.0.2
  cloud_functions: ^6.0.2
  flutter_hooks: ^0.21.3+1
  hooks_riverpod: ^3.0.0
  flutter_riverpod: ^3.0.0
  go_router: ^16.2.4
  freezed_annotation: ^3.1.0
  json_annotation: ^4.9.0
  intl: ^0.20.2
  equatable: ^2.0.5
  uuid: ^4.4.0
  collection: ^1.18.0
  async: ^2.11.0
  url_launcher: ^6.3.0
  flutter_local_notifications: ^19.4.2
  google_sign_in: ^7.2.0
  sign_in_with_apple: ^7.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  build_runner: ^2.7.1
  freezed: ^3.2.3
  json_serializable: ^6.8.0
  mocktail: ^1.0.3

flutter:
  uses-material-design: true
  assets:
    - assets/
