// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        return linux;
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCGRj1DBJbWX-qRHkyCiVFoUNMNDrRK6gA',
    appId: '1:769568338259:web:2489f6cdb1831d1445f1a6',
    messagingSenderId: '769568338259',
    projectId: 'nms-dev-koudelkab',
    authDomain: 'nms-dev-koudelkab.firebaseapp.com',
    storageBucket: 'nms-dev-koudelkab.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBb9RF9U-pztksOao-dU1H4hwg0gC13EH0',
    appId: '1:769568338259:android:360aad776752667945f1a6',
    messagingSenderId: '769568338259',
    projectId: 'nms-dev-koudelkab',
    storageBucket: 'nms-dev-koudelkab.firebasestorage.app',
  );

  static const FirebaseOptions linux = FirebaseOptions(
    apiKey: 'AIzaSyCGRj1DBJbWX-qRHkyCiVFoUNMNDrRK6gA',
    appId: '1:769568338259:web:2489f6cdb1831d1445f1a6',
    messagingSenderId: '769568338259',
    projectId: 'nms-dev-koudelkab',
    authDomain: 'nms-dev-koudelkab.firebaseapp.com',
    storageBucket: 'nms-dev-koudelkab.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCGRj1DBJbWX-qRHkyCiVFoUNMNDrRK6gA',
    appId: '1:769568338259:web:ed12334da077738c45f1a6',
    messagingSenderId: '769568338259',
    projectId: 'nms-dev-koudelkab',
    authDomain: 'nms-dev-koudelkab.firebaseapp.com',
    storageBucket: 'nms-dev-koudelkab.firebasestorage.app',
  );

}